# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-01 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=4, verbose_name='评分')),
                ('comment_content', models.CharField(default='东西强烈好评', max_length=255, verbose_name='评论内容')),
                ('comment_time', models.DateTimeField(auto_now=True, verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '商品评论表',
                'verbose_name_plural': '商品评论表',
                'db_table': 'order_comment',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_id', models.IntegerField(verbose_name='商品id')),
                ('g_num', models.IntegerField(verbose_name='商品数量')),
                ('g_price', models.FloatField(verbose_name='商品价格')),
            ],
            options={
                'verbose_name': '商品订单表',
                'verbose_name_plural': '商品订单表',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('o_num', models.IntegerField(primary_key=True, serialize=False, verbose_name='订单号')),
                ('o_addr', models.CharField(default='', max_length=255, verbose_name='收货地址')),
                ('o_conn', models.CharField(default='', max_length=20, verbose_name='联系电话')),
                ('o_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('o_status', models.IntegerField(choices=[(0, '待付款'), (1, '待收货'), (2, '待评价')], default=0, verbose_name='订单状态')),
                ('o_total', models.FloatField(blank=True, null=True, verbose_name='订单总价')),
                ('o_relpay', models.FloatField(blank=True, null=True, verbose_name='实际支付')),
                ('o_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsDetails', verbose_name='关联商品')),
                ('o_shopper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.JdShopper', verbose_name='关联商户')),
                ('o_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.JdUser', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '订单详情表',
                'verbose_name_plural': '订单详情表',
                'db_table': 'o_detail',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='o_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderDetail', verbose_name='关联订单详情表'),
        ),
        migrations.AddField(
            model_name='goodscomment',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderDetail', verbose_name='订单id'),
        ),
    ]
