# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-26 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JdOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.JdUser', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '订单列表',
                'verbose_name_plural': '订单列表',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_shopper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.JdShopper', verbose_name='关联商户')),
            ],
            options={
                'verbose_name': '订单详情表',
                'verbose_name_plural': '订单详情表',
                'db_table': 'order_detail',
            },
        ),
    ]
