# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-28 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='o_o',
            field=models.FloatField(blank=True, null=True, verbose_name='实际支付'),
        ),
    ]
