# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-28 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderdetail_o_o'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='o_o',
        ),
    ]
