# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-02 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190701_2102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderList',
        ),
        migrations.AlterModelTable(
            name='orderlist',
            table='order_list',
        ),
    ]
