# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-02 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20190701_2102'),
        ('orders', '0003_auto_20190702_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrouBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gbn', models.IntegerField(blank=True, default=10, null=True, verbose_name='允许拼够人数')),
                ('gbp', models.IntegerField(blank=True, default=0, null=True, verbose_name='已拼购人数')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsDetails', verbose_name='关联商品')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderDetail', verbose_name='关联订单')),
            ],
            options={
                'verbose_name': '商品评论表',
                'verbose_name_plural': '商品评论表',
                'db_table': 'group_buy',
            },
        ),
    ]
