# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-02 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_groubuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='groubuy',
            name='buy_price',
            field=models.FloatField(blank=True, null=True, verbose_name='拼购价格'),
        ),
    ]
