# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_groubuy_buy_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodscomment',
            name='order_id',
        ),
        migrations.AddField(
            model_name='goodscomment',
            name='goods_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='商品id'),
        ),
    ]
