# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-04 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.CharField(blank=True, max_length=255, null=True, verbose_name='文字')),
                ('price', models.FloatField(verbose_name='拍卖价格')),
                ('clickcount', models.IntegerField(default=10, verbose_name='访问数量')),
            ],
            options={
                'verbose_name': '拍卖表',
                'verbose_name_plural': '拍卖表',
                'db_table': 'goods_auction',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户id')),
                ('cop_id', models.IntegerField(verbose_name='优惠券id')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='使用场景')),
                ('vuc', models.IntegerField(blank=True, choices=[(0, '无门槛优惠券'), (1, '满减优惠券')], default=0, null=True, verbose_name='使用规则(0/1)')),
                ('minusprice', models.FloatField(blank=True, null=True, verbose_name='优惠价格')),
            ],
            options={
                'verbose_name': '优惠券表',
                'verbose_name_plural': '优惠券表',
                'db_table': 'jd_coupon',
            },
        ),
        migrations.CreateModel(
            name='GoodsDetails',
            fields=[
                ('goods_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='商品编号')),
                ('goods_img', models.CharField(blank=True, max_length=255, null=True, verbose_name='商品展示图片')),
                ('goods_name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='商品名称')),
                ('goods_prices', models.FloatField(blank=True, default=0, max_length=50, null=True, verbose_name='商品单价')),
                ('kill_prices', models.FloatField(blank=True, default=0, max_length=50, null=True, verbose_name='秒杀价格')),
                ('goods_num', models.IntegerField(blank=True, default=1, null=True, verbose_name='商品库存')),
                ('goods_state', models.IntegerField(blank=True, choices=[(0, '下架'), (1, '上架')], default=1, null=True, verbose_name='商品上架状态')),
                ('one_category_id', models.IntegerField(blank=True, null=True, verbose_name='一级分类id')),
                ('two_category_id', models.IntegerField(blank=True, null=True, verbose_name='二级分类id')),
                ('keywords', models.CharField(blank=True, max_length=50, null=True, verbose_name='关键字')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('sales', models.IntegerField(blank=True, default=0, null=True, verbose_name='销量')),
                ('label', models.CharField(blank=True, max_length=100, null=True, verbose_name='标签')),
                ('rate', models.CharField(blank=True, max_length=100, null=True, verbose_name='好评率')),
                ('evaluate', models.IntegerField(blank=True, null=True, verbose_name='评价条数')),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.JdShopper', verbose_name='店铺id')),
            ],
            options={
                'verbose_name': '商品详细表',
                'verbose_name_plural': '商品详细表',
                'db_table': 'goods_details',
            },
        ),
        migrations.CreateModel(
            name='GoodsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_urls', models.CharField(blank=True, max_length=2000, null=True, verbose_name='商品详情图片')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsDetails', verbose_name='关联商品')),
            ],
            options={
                'verbose_name': '商品图片表',
                'verbose_name_plural': '商品图片表',
                'db_table': 'goods_imgs',
            },
        ),
        migrations.CreateModel(
            name='GoodsRec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=30, verbose_name='页面名称')),
                ('img_urls', models.CharField(max_length=200, verbose_name='图片链接')),
                ('remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='备注')),
                ('one_category_id', models.IntegerField(verbose_name='推荐商品分类id')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsDetails', verbose_name='关联商品')),
            ],
            options={
                'verbose_name': '商品推荐表',
                'verbose_name_plural': '商品推荐表',
                'db_table': 'goods_rec',
            },
        ),
        migrations.CreateModel(
            name='GoodsSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.IntegerField(verbose_name='商品id')),
                ('goods_num', models.IntegerField(blank=True, default=1, null=True, verbose_name='商品库存')),
                ('properties', models.CharField(blank=True, max_length=200, null=True, verbose_name='属性')),
            ],
            options={
                'verbose_name': '商品属性规格表',
                'verbose_name_plural': '商品属性规格表',
                'db_table': 'goods_sku',
            },
        ),
        migrations.CreateModel(
            name='GoodsType1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_type_id', models.IntegerField(verbose_name='一级分类id')),
                ('one_type_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='一级分类名称')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('type_img', models.CharField(blank=True, max_length=255, null=True, verbose_name='一级分类图片')),
            ],
            options={
                'verbose_name': '商品分类表',
                'verbose_name_plural': '商品分类表',
                'db_table': 'goods_type1',
            },
        ),
        migrations.CreateModel(
            name='GoodsType2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_type_id', models.IntegerField(verbose_name='二级分类id')),
                ('two_type_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='二级分类名称')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('type_img', models.CharField(blank=True, max_length=255, null=True, verbose_name='二级分类图片')),
            ],
            options={
                'verbose_name': '商品分类表',
                'verbose_name_plural': '商品分类表',
                'db_table': 'goods_type2',
            },
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=30, verbose_name='页面名称')),
                ('img_urls', models.CharField(max_length=200, verbose_name='图片链接')),
                ('remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='备注')),
                ('page_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='文字内容')),
            ],
            options={
                'verbose_name': '导航表',
                'verbose_name_plural': '导航表',
                'db_table': 'nav',
            },
        ),
        migrations.CreateModel(
            name='ShopperImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, max_length=2000, null=True, verbose_name='关联商品详细图片')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片类别')),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.JdShopper', verbose_name='关联商户')),
            ],
            options={
                'verbose_name': '商铺详情图片',
                'verbose_name_plural': '商铺详情图片',
                'db_table': 'shopper_img',
            },
        ),
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=30, verbose_name='页面名称')),
                ('img_urls', models.CharField(max_length=200, verbose_name='图片链接')),
                ('remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '轮播图表',
                'verbose_name_plural': '轮播图表',
                'db_table': 'slideshow',
            },
        ),
        migrations.AddField(
            model_name='auction',
            name='goods_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsDetails', verbose_name='商品id'),
        ),
    ]
