# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-04 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsimages',
            name='img_urls',
            field=models.TextField(blank=True, null=True, verbose_name='商品详情图片'),
        ),
        migrations.AlterField(
            model_name='shopperimg',
            name='img',
            field=models.TextField(blank=True, null=True, verbose_name='关联商品详细图片'),
        ),
    ]
