# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-01 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsdetails',
            old_name='good_img',
            new_name='goods_img',
        ),
        migrations.RenameField(
            model_name='goodsdetails',
            old_name='lable',
            new_name='label',
        ),
    ]
