# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-01 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190701_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsdetails',
            name='goods_state',
            field=models.IntegerField(choices=[(0, '下架'), (1, '上架')], default=1, verbose_name='商品上架状态'),
        ),
    ]
