# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-01 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190701_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsseckill',
            name='goods_id',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='minusprice',
            field=models.FloatField(blank=True, null=True, verbose_name='优惠价格'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='vuc',
            field=models.IntegerField(blank=True, choices=[(0, '无门槛优惠券'), (1, '满减优惠券')], default=0, null=True, verbose_name='使用规则(0/1)'),
        ),
        migrations.AlterField(
            model_name='goodsdetails',
            name='goods_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='goodsdetails',
            name='goods_num',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='商品库存'),
        ),
        migrations.AlterField(
            model_name='goodsdetails',
            name='goods_prices',
            field=models.FloatField(blank=True, default=0, max_length=50, null=True, verbose_name='商品单价'),
        ),
        migrations.AlterField(
            model_name='goodsdetails',
            name='goods_state',
            field=models.IntegerField(blank=True, choices=[(0, '下架'), (1, '上架')], default=1, null=True, verbose_name='商品上架状态'),
        ),
        migrations.AlterField(
            model_name='goodsdetails',
            name='keywords',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='关键字'),
        ),
        migrations.AlterField(
            model_name='goodsdetails',
            name='kill_prices',
            field=models.FloatField(blank=True, default=0, max_length=50, null=True, verbose_name='秒杀价格'),
        ),
        migrations.AlterField(
            model_name='goodsdetails',
            name='one_category_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='一级分类id'),
        ),
        migrations.AlterField(
            model_name='goodsdetails',
            name='sales',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='销量'),
        ),
        migrations.AlterField(
            model_name='goodsdetails',
            name='two_category_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='二级分类id'),
        ),
        migrations.AlterField(
            model_name='goodsimages',
            name='img_urls',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='商品详情图片'),
        ),
        migrations.AlterField(
            model_name='goodsrec',
            name='remark',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='goodssku',
            name='goods_num',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='商品库存'),
        ),
        migrations.AlterField(
            model_name='goodstype1',
            name='one_type_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='一级分类名称'),
        ),
        migrations.AlterField(
            model_name='goodstype1',
            name='type_img',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='一级分类图片'),
        ),
        migrations.AlterField(
            model_name='goodstype2',
            name='two_type_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='二级分类名称'),
        ),
        migrations.AlterField(
            model_name='goodstype2',
            name='type_img',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='二级分类图片'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='remark',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='remark',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备注'),
        ),
        migrations.DeleteModel(
            name='GoodsSeckill',
        ),
    ]
