# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-05 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190705_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsdetails',
            name='kill_prices',
            field=models.FloatField(blank=True, default=0, max_length=50, null=True, verbose_name='优惠价格'),
        ),
    ]
