# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-05 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20190705_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsdetails',
            name='evaluate',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='评价条数'),
        ),
    ]
