# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-02 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20190702_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstype1',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='goodstype2',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
    ]
