# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20190702_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsdetails',
            name='rate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='好评率'),
        ),
        migrations.AddField(
            model_name='shopperimg',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='图片类别'),
        ),
    ]
