# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20190703_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopperimg',
            name='goods_img',
        ),
        migrations.AddField(
            model_name='shopperimg',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='关联商品详细图片'),
        ),
    ]
