# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20190703_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsdetails',
            name='evaluate',
            field=models.IntegerField(blank=True, null=True, verbose_name='评价条数'),
        ),
    ]
