# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-03 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_goodsdetails_evaluate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopperimg',
            options={'verbose_name': '商铺详情图片', 'verbose_name_plural': '商铺详情图片'},
        ),
        migrations.AlterField(
            model_name='shopperimg',
            name='img',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='关联商品详细图片'),
        ),
    ]
