# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-04 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clt_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏id')),
                ('type_id', models.IntegerField(blank=True, choices=[(0, '商品'), (1, '商户')], default=0, null=True, verbose_name='商品/商户')),
            ],
            options={
                'verbose_name': '收藏表',
                'verbose_name_plural': '收藏表',
                'db_table': 'u_clt',
            },
        ),
        migrations.CreateModel(
            name='JdShopper',
            fields=[
                ('m_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='商铺名称')),
                ('m_username', models.CharField(blank=True, max_length=50, null=True, verbose_name='商主名称')),
                ('m_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='商户ID')),
                ('m_pwd', models.CharField(blank=True, max_length=200, null=True, verbose_name='密码')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='注册时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('is_active', models.IntegerField(blank=True, choices=[(0, '未登录'), (1, '已登录')], default=1, null=True, verbose_name='登陆状态')),
                ('m_img', models.ImageField(blank=True, default='qw.jpg', null=True, upload_to='media', verbose_name='商户图片')),
                ('m_email', models.CharField(blank=True, max_length=50, null=True, verbose_name='商户邮箱')),
                ('m_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='手机号')),
                ('s_add', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('is_delete', models.IntegerField(blank=True, choices=[(0, '未删除'), (1, '已删除')], default=0, null=True, verbose_name='删除标识位')),
                ('is_val', models.IntegerField(blank=True, choices=[(0, '未验证'), (1, '已验证')], default=1, null=True, verbose_name='验证标识位')),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='备注')),
                ('clt', models.IntegerField(blank=True, null=True, verbose_name='收藏人数')),
            ],
            options={
                'verbose_name': '商户表',
                'verbose_name_plural': '商户表',
                'db_table': 'jd_shopper',
            },
        ),
        migrations.CreateModel(
            name='JdUser',
            fields=[
                ('user_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户名')),
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='用户ID')),
                ('auth_string', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户密码')),
                ('is_val', models.IntegerField(blank=True, choices=[(0, '未验证'), (1, '已验证')], default=0, null=True, verbose_name='是否验证')),
                ('tel', models.CharField(blank=True, max_length=15, null=True, verbose_name='联系电话')),
                ('asset', models.FloatField(blank=True, default=0, null=True, verbose_name='余额')),
                ('u_img', models.ImageField(blank=True, default='qw.jpg', null=True, upload_to='media', verbose_name='用户头像')),
                ('u_bank', models.CharField(blank=True, max_length=50, null=True, verbose_name='银行卡')),
                ('user_card', models.CharField(blank=True, max_length=50, null=True, verbose_name='身份证号')),
                ('pay_pwd', models.CharField(blank=True, max_length=6, null=True, verbose_name='支付密码')),
                ('u_email', models.CharField(blank=True, max_length=20, null=True, verbose_name='邮箱')),
                ('u_real', models.CharField(blank=True, max_length=20, null=True, verbose_name='真实姓名')),
                ('u_intg', models.IntegerField(default=0, verbose_name='用户积分')),
                ('is_delete', models.IntegerField(blank=True, choices=[(0, '未删除'), (1, '已删除')], default=0, null=True, verbose_name='删除标识位')),
            ],
            options={
                'verbose_name': '用户信息表',
                'verbose_name_plural': '用户信息表',
                'db_table': 'jd_user',
            },
        ),
        migrations.CreateModel(
            name='ShopperType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='商铺分类名称')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.JdShopper', verbose_name='关联商户')),
            ],
            options={
                'verbose_name': '商铺详情图片',
                'verbose_name_plural': '商铺详情图片',
                'db_table': 'shopper_type',
            },
        ),
        migrations.CreateModel(
            name='UAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='收货地址')),
                ('is_default', models.IntegerField(choices=[(0, '选择'), (1, '不选择')], default=0, verbose_name='默认地址')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.JdUser', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '地址表',
                'verbose_name_plural': '地址表',
                'db_table': 'u_address',
            },
        ),
        migrations.AddField(
            model_name='collectgoods',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.JdUser', verbose_name='用户id'),
        ),
    ]
