# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-05 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190705_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jduser',
            name='pay_pwd',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='支付密码'),
        ),
    ]
