# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-05 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190705_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jdshopper',
            name='m_img',
            field=models.TextField(blank=True, null=True, verbose_name='****'),
        ),
        migrations.AlterField(
            model_name='jduser',
            name='u_img',
            field=models.TextField(blank=True, null=True, verbose_name='用户头像地址'),
        ),
    ]
