# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-01 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jdcart',
            name='c_freight',
            field=models.FloatField(blank=True, null=True, verbose_name='运费'),
        ),
        migrations.AlterField(
            model_name='jdcart',
            name='c_goods_num',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='商品数量'),
        ),
    ]
